# Generated by Django 5.1.4 on 2026-07-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RGPDRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        help_text="Email de l'utilisateur ayant formulé la demande", max_length=254
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("export", "Export de données"),
                            ("delete", "Suppression de compte"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Log Audit RGPD",
                "verbose_name_plural": "Logs Audit RGPD",
                "ordering": ["-timestamp"],
            },
        ),
    ]
