# Generated by Django 5.1.4 on 2026-07-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rgpdrequestlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("student", "Étudiant"), ("teacher", "Enseignant")],
                default="student",
                help_text="Rôle de l'utilisateur sur la plateforme.",
                max_length=10,
            ),
        ),
    ]
