# Generated by Django 5.1.4 on 2026-07-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_role"),
        ("accounts", "0002_rgpdrequestlog"),
    ]

    operations = []
