# Generated by Django 5.1.4 on 2026-07-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="rgpdrequestlog",
            name="file_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 de l'archive/JSON renvoyé à l'utilisateur (intégrité de la réponse SAR).",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="rgpdrequestlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("received", "Reçue"),
                    ("processing", "En cours"),
                    ("answered", "Répondue"),
                ],
                default="received",
                max_length=15,
            ),
        ),
    ]
