# Generated by Django 5.1.4 on 2026-07-01 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_question_selected_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du cours (saisi ou déduit du nom de fichier PDF).', max_length=200)),
                ('content', models.TextField(help_text='Texte brut du cours (extrait PDF ou saisie utilisateur).')),
                ('source', models.CharField(choices=[('pdf', 'PDF uploadé'), ('text', 'Texte collé')], help_text='Origine du contenu : PDF uploadé ou texte collé.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Propriétaire du cours.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-created_at'],
            },
        ),
    ]
