# Generated by Django 5.1.4 on 2026-07-01 20:26

from django.db import migrations, models
from django.db.models import Count


def backfill_status(apps, schema_editor):
    """Requalifie les quiz existants : 10 questions → completed, sinon failed.

    Les quiz créés avant ce champ étaient tous « generating » par défaut ;
    or ceux à 0 question sont en réalité des générations échouées (timeout
    Ollama, JSON invalide…). On les marque « failed » pour les sortir de
    l'état bloqué et éviter les cartes mortes dans l'historique.
    """
    Quiz = apps.get_model("quizzes", "Quiz")
    annotated = Quiz.objects.annotate(nb=Count("questions"))
    annotated.filter(nb=10).update(status="completed")
    annotated.exclude(nb=10).update(status="failed")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0003_question_chapter"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="status",
            field=models.CharField(
                choices=[
                    ("generating", "En cours de génération"),
                    ("completed", "Terminé"),
                    ("failed", "Échec"),
                ],
                default="generating",
                help_text="Statut de la génération LLM (generating / completed / failed).",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_status, noop),
    ]
