# Generated by Django 5.1.4 on 2026-07-01 20:38

from django.db import migrations


def _fix(text: str) -> str:
    """Décode uniquement les apostrophes/guillemets sur-échappés.

    On NE touche PAS &lt; &gt; &amp; : les balises restent neutralisées (XSS).
    On corrige seulement ce que l'ancien html.escape(quote=True) avait cassé
    dans du texte normal ("Qu&#x27;est-ce" → "Qu'est-ce").
    """
    if not isinstance(text, str):
        return text
    return text.replace("&#x27;", "'").replace("&#39;", "'").replace("&quot;", '"')


def unescape_quotes(apps, schema_editor):
    Question = apps.get_model("quizzes", "Question")
    to_update = []
    for q in Question.objects.all():
        new_prompt = _fix(q.prompt)
        new_options = [_fix(o) for o in q.options] if isinstance(q.options, list) else q.options
        if new_prompt != q.prompt or new_options != q.options:
            q.prompt = new_prompt
            q.options = new_options
            to_update.append(q)
    if to_update:
        Question.objects.bulk_update(to_update, ["prompt", "options"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("quizzes", "0004_quiz_status"),
    ]

    operations = [
        migrations.RunPython(unescape_quotes, noop),
    ]
